### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Rahuuuul** [Magikcraft/product-board#26]
.

**Comment by jwulf** [comment]
Hi @rosk2006 thanks for opening this issue. I have not forgotten about it.

@Technosasquach - what will it take to add plots back in to Magikcraft again?

**Comment by Technosasquach** [comment]
The plot ability has been in the game since day one. Just give me a server and world and it can be done instantly.
In that requirements, there are two things that are currently very difficult. 
1. Disallowing magic in a area is impossible. I've been asking for it for ages but ive never seen it implimented.
2. Is the monetry aspect. We have no way currently for anyone to make money, to that end, there is nothing in setup to handle it. I can enable it, but i cant give any projection or timeline for it

**Comment by Rahuuuul** [comment]
Hi @jwulf and @Technosasquach. We could combine the Magikcraft lobby idea and the Plot idea to create one world. We could do this by putting the lobby in the middle of the world, with all the plots around it and putting a area where you can get items for free from a command block. To do this i will be happy to build it but i will need permissions to build and put down command blocks. The command blocks will not be able to be tampered with.

**Comment by Rahuuuul** [comment]
@Technosasquach couldn't we just not have the magikcraft mod in that world?

**Comment by jwulf** [comment]
@Technosasquach what's involved in it? For example: on the current production server at play.magikcraft.io does anything need to be done to the configuration in the image, or is it something that is done at runtime?

To the money aspect - we are currently working on Bitcoin mining in Magikcraft.

**Comment by Technosasquach** [comment]
Plots have been added in, with the understanding of action that @jwulf is to block magik on the plots or persistent/plots world

**Comment by jwulf** [comment]
Great work @Technosasquach - thanks!

A couple of things:

1. How do users get to the plots world?
   * When they join for the first time.
   * Any time they join.
2. Currently users can claim a plot, but cannot build / mine in their plot. 
See: https://www.youtube.com/watch?v=x_MM-p4G__M

**Comment by Technosasquach** [comment]
To access the plots world, the users need to go to the lobby world, which is the world 'world' currently. There are two portals there, one for mining and another for the plots. Both are marked. And since players are spawned in the plots world on a new join, they have instant access
The problem with users not being able to build in the plots is due to the permissions. IE Players are unable to build anywhere. I did update the permissions to allow the loophole on the world plots and mining but it must not be working. Ill look at it again when i get an opotunity

**Comment by jwulf** [comment]
On a server update, I spawn in ljblockbuster's lounge world `world-blockbuster`.

**Comment by Rahuuuul** [comment]
hey @Technosasquach I can't find the lobby or the plots whenever I join. is it supposed to be like that or are you still working on it?
