### ISSUE TITLE
Lore push does not happen if user unassociated

### ISSUE THREAD

**Issue by jwulf** [Magikcraft/product-board#46]
Observed while Xx_MEDIARITE_xX was recording a video:

If a user is unassociated, and associates in the tutorial level by typing `/magik.volare` and clicking the link, their spellbook opens, they are associated, and the `magik.volare` scroll is not visible in their spellbook.

This is because the lore push event is emitted before association. We probably need to buffer these events, and replay them on association.

Otherwise the user is left with: "I typed it in and clicked the link, but it didn't work."

Since they just did that, they predict that doing the same thing again will not produce a different result, and so don't think of trying it again.

**Comment by tim-marwick** [comment]
@jwulf as discussed, this is because when Ruben first started paying on your machine, as your Minecraft user, he was not "unassociated", rather he was associated with your Github user.

I tested again and can confirm that when truely unassociated, all `playerEvent`s get logged against a `placeholder` user, and upon association, get transferred to the newly associated user.

This case outlined in this issue is really an edge case which will never effect 99% of users, and so I am going mark it "won't fix" (for now), and close it.
