### ISSUE TITLE
Scrolls disappear in spellbook

### ISSUE THREAD

**Issue by jwulf** [Magikcraft/product-board#56]
In this case, the user got a bunch of scrolls, then associated their Minecraft user with a different GitHub account, then associated it back with their GitHub account.

After some time we noticed that the scrolls were gone from the spellbook. Attempting to insert a new scroll by typing `/magik.incendium` in Minecraft causes the event to trigger, but no scroll to show up in the spellbook.

<img width="1105" alt="screen shot 2017-12-30 at 1 03 20 pm" src="https://user-images.githubusercontent.com/406975/34449850-2a6627b4-ed62-11e7-8c0b-1f02d52025ff.png">

**Comment by jwulf** [comment]
Here is what it looks like on the endpoint when doing it:

<img width="795" alt="screen shot 2017-12-30 at 1 08 56 pm" src="https://user-images.githubusercontent.com/406975/34449882-a2ab055a-ed62-11e7-95e2-48efbc55a526.png">

**Comment by jwulf** [comment]
The user is `HappyFaceLoL`

**Comment by tim-marwick** [comment]
@jwulf I fixed the missing scrolls issue. We have a web hook that pulls in the scrolls from `Magikcraft/magikcraft-lore-core`, but somehow it didn’t make a complete import after you pushed an update yest. 

https://github.com/Magikcraft/magikcraft-lore-core/commits/master

Could be due to exhausting the github rate_limit

Anyways, the fix was simple. I just ran this in Graphiql https://play.magikcraft.io/graphiql

 ```
mutation {
  importScrollsFromPackage(packageFullname: "Magikcraft/magikcraft-lore-core", packageBranchname: "master")
}
```
That triggers the import action, same as is triggered by the web hook mentioned above.

Not going to do any deeper investigation into the root cause of this at this time, as it appears to be working, and a simple manual check is sufficient after pushing updates to `Magikcraft/magikcraft-lore-core` is sufficient for the meantime.

For the manual check, run this against the database:

`SELECT * FROM scroll WHERE package_fullname = 'Magikcraft/magikcraft-lore-core' AND package_branchname = 'master'`

I'll look more into guarding against possible root causes when I revisit scrolls integration post ScriptCraft migration.
